# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top.xdc

# IP: ip/ram_32_16k/ram_32_16k.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ram_32_16k || ORIG_REF_NAME==ram_32_16k} -quiet] -quiet

# IP: ip/ram_16_32k/ram_16_32k.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ram_16_32k || ORIG_REF_NAME==ram_16_32k} -quiet] -quiet

# IP: ip/ram_8_64k/ram_8_64k.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ram_8_64k || ORIG_REF_NAME==ram_8_64k} -quiet] -quiet

# XDC: ip/ram_32_16k/ram_32_16k_ooc.xdc

# XDC: ip/ram_16_32k/ram_16_32k_ooc.xdc

# XDC: ip/ram_8_64k/ram_8_64k_ooc.xdc
